### ISSUE TITLE
Lack of Scope/Kind Checking let rec annotations

### ISSUE THREAD

**Issue by maxsnew** [zydeco-lang/zydeco#28] opened 2022-12-05 21:12 UTC
```
let rec loop : Foo = ( ! loop );

! exit 0
```

Expected: `Unbound type variable Foo`
What I get: runs fine.

**Comment by LighghtEeloo** [comment] 2022-12-07 12:49
Bug confirmed. The cause was that the type validation in type annotations were not recursive. Say we've got an `A` type, if it's a type variable syntactically, we would check; but if it's `Thunk(B)`, we would just let it pass.

Addressed in 7b72cae25b953e6ace61c67ff36885ca3a7c365c.

**Comment by LighghtEeloo** [comment] 2023-03-16 17:51
Fixed on main.

**Closed by LighghtEeloo** 2023-03-16 17:51 UTC
Labels: bug
